added yml and api endpoint for gforms

diff --git a/.github/workflows/gravityforms&addons.yml b/.github/workflows/gravityforms&addons.yml
--- a/.github/workflows/gravityforms&addons.yml
+++ b/.github/workflows/gravityforms&addons.yml
@@ -1,45 +1,51 @@
-name: Check WordPress Plugin SVN Updates For Gravity Forms And Addons
+name: Check WordPress Plugin Version Updates
 
 on:
   push:
     branches:
-      - maind
+      - stagings
   schedule:
     - cron: '0 * * * *' # Runs every hour
   workflow_dispatch: # Allow manual trigger
 
 jobs:
-  check-svn-updates:
+  check-plugin-version:
     runs-on: ubuntu-latest
 
     strategy:
       matrix:
         plugin:
           - simple-cloudflare-turnstile
-          - gravity
-          - hcaptcha-for-forms-and-more
+          - wpforms-lite
           - akismet
+          - gravityforms
           # Add more plugins here
 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
-
-      - name: Set up SVN
-        run: sudo apt-get install -y subversion
-
-      - name: Check for latest SVN revision
-        id: check-svn
+      - name: Get plugin version from WordPress site
+        id: get-plugin-version
         run: |
-          plugin_name=${{ matrix.plugin }}
-          svn info https://plugins.svn.wordpress.org/$plugin_name/trunk | grep 'Last Changed Rev' | awk '{print $4}' > ".revision/${plugin_name}_current_revision_gravityform.txt"
+          plugin_slug=${{ matrix.plugin }}
+          response=$(curl -s "https://your-wordpress-site.com/wp-json/checkview/v1/plugin-version?_plugin_slug=$plugin_slug")
+          plugin_version=$(echo $response | jq -r '.version')
 
-      - name: Get previous SVN revision
+          if [ "$plugin_version" == "null" ] || [ -z "$plugin_version" ]; then
+            echo "Plugin version not found for $plugin_slug"
+            exit 1
+          else
+            echo "Plugin version for $plugin_slug is $plugin_version"
+            echo "::set-output name=plugin_version::$plugin_version"
+            # Save the plugin version to the current revision file
+            current_revision_file=".revision/${plugin_name}_current_revision_gravityforms.txt"
+            echo "$plugin_version" > "$current_revision_file"
+          fi
+
+      - name: Get previous plugin version
         id: get-previous
         run: |
           plugin_name=${{ matrix.plugin }}
-          if [ -f ".revision/${plugin_name}_latest_revision_gravityform.txt" ]; then
-            cat ".revision/${plugin_name}_latest_revision_gravityform.txt"
+          if [ -f ".revision/${plugin_name}_latest_revision_gravityforms.txt" ]; then
+            cat ".revision/${plugin_name}_latest_revision_gravityforms.txt"
           else
             echo "0"
           fi
@@ -49,11 +55,11 @@ jobs:
         id: compare-revisions
         run: |
           plugin_name=${{ matrix.plugin }}
-          current_revision=$(cat ".revision/${plugin_name}_current_revision_gravityform.txt")
+          current_revision=$(cat ".revision/${plugin_name}_current_revision_gravityforms.txt")
           
           # Check if the previous revision file exists
-          if [ -f ".revision/${plugin_name}_latest_revision_gravityform.txt" ]; then
-            previous_revision=$(cat ".revision/${plugin_name}_latest_revision_gravityform.txt")
+          if [ -f ".revision/${plugin_name}_latest_revision_gravityforms.txt" ]; then
+            previous_revision=$(cat ".revision/${plugin_name}_latest_revision_gravityforms.txt")
           else
             previous_revision="0"
           fi
@@ -63,7 +69,6 @@ jobs:
 
           if [ "$current_revision" -gt "$previous_revision" ]; then
             echo "${plugin_name}_update_found=true" >> $GITHUB_ENV
-            echo "current_revision=$current_revision" >> $GITHUB_ENV
             echo "::set-output name=${plugin_name}_update_found::true"
           else
             echo "${plugin_name}_update_found=false" >> $GITHUB_ENV
@@ -75,7 +80,7 @@ jobs:
         run: |
           plugin_name=${{ matrix.plugin }}
           mkdir -p .revision
-          cp ".revision/${plugin_name}_current_revision_gravityform.txt" ".revision/${plugin_name}_latest_revision_gravityform.txt"
+          cp ".revision/${plugin_name}_current_revision_gravityforms.txt" ".revision/${plugin_name}_latest_revision_gravityforms.txt"
 
       - name: Commit updated revision file
         if: steps.compare-revisions.outputs.${{ matrix.plugin }}_update_found == 'true'
@@ -91,26 +96,16 @@ jobs:
 
           # Apply the stashed changes back after the pull
           git stash pop || echo "No changes to apply from stash"
-          git add ".revision/${plugin_name}_latest_revision_gravityform.txt"
+          git add ".revision/${plugin_name}_latest_revision_gravityforms.txt"
           if ! git diff-index --quiet HEAD; then
             git commit -m "Update $plugin_name SVN revision"
             git push
           else
             echo "No changes to commit"
           fi
-      - name: Create Gravity Forms & hCaptcha Site for Testing in InstaWP
-        if: ${{ ( steps.compare-revisions.outputs.gravity_update_found == 'true' ) || ( steps.compare-revisions.outputs.hcaptcha-for-forms-and-more_update_found == 'true' ) }}
-        uses: instawp/wordpress-testing-automation@main
-        with:
-            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
-            INSTAWP_TEMPLATE_SLUG: gravity-forms--hcaptcha-for-wp
-            REPO_ID: 521
-            EXPIRY_HOURS: 1
-            INSTAWP_ACTION: create-site-template
             
       - name: Create Gravity Forms & hCaptcha native Site for Testing in InstaWP
-        if: steps.compare-revisions.outputs.gravity_update_found == 'true' 
+        if: steps.compare-revisions.outputs.gravityforms_update_found == 'true' 
         uses: instawp/wordpress-testing-automation@main
         with:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -121,7 +116,7 @@ jobs:
             INSTAWP_ACTION: create-site-template
 
       - name: Create Gravity Forms Trusntile for Testing in InstaWP
-        if: ${{ ( steps.compare-revisions.outputs.gravity_update_found == 'true' ) || ( steps.compare-revisions.outputs.simple-cloudflare-turnstile_update_found == 'true' ) }}
+        if: ${{ ( steps.compare-revisions.outputs.gravityforms_update_found == 'true' ) || ( steps.compare-revisions.outputs.simple-cloudflare-turnstile_update_found == 'true' ) }}
         uses: instawp/wordpress-testing-automation@main
         with:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -132,7 +127,7 @@ jobs:
             INSTAWP_ACTION: create-site-template
 
       - name: Create FluentForms Trusntile Natvie for Testing in InstaWP
-        if: steps.compare-revisions.outputs.gravity_update_found == 'true'
+        if: steps.compare-revisions.outputs.gravityforms_update_found == 'true'
         uses: instawp/wordpress-testing-automation@main
         with:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -143,7 +138,7 @@ jobs:
             INSTAWP_ACTION: create-site-template
             
       - name: Create Gravity Forms With Akismet Site for Testing in InstaWP
-        if: ${{ ( steps.compare-revisions.outputs.gravity_update_found == 'true' ) || ( steps.compare-revisions.outputs.akismet_update_found== 'true' ) }}
+        if: ${{ ( steps.compare-revisions.outputs.gravityforms_update_found == 'true' ) || ( steps.compare-revisions.outputs.akismet_update_found== 'true' ) }}
         uses: instawp/wordpress-testing-automation@main
         with:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -154,7 +149,7 @@ jobs:
             INSTAWP_ACTION: create-site-template
 
       - name: Create Gravity Forms With ReCaptcha v3 Native Site for Testing in InstaWP
-        if: steps.compare-revisions.outputs.gravity_update_found == 'true'
+        if: steps.compare-revisions.outputs.gravityforms_update_found == 'true'
         uses: instawp/wordpress-testing-automation@main
         with:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -164,19 +159,9 @@ jobs:
             EXPIRY_HOURS: 1
             INSTAWP_ACTION: create-site-template
 
-      - name: Create Gravity Forms With ReCaptcha v2 Native Site for Testing in InstaWP
-        if: steps.compare-revisions.outputs.gravity_update_found == 'true'
-        uses: instawp/wordpress-testing-automation@main
-        with:
-            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-            INSTAWP_TOKEN: ${{ secrets.INSTAWP_TOKEN }}
-            INSTAWP_TEMPLATE_SLUG: gravity-forms--recaptcha-v2-native
-            REPO_ID: 521
-            EXPIRY_HOURS: 1
-            INSTAWP_ACTION: create-site-template
 
       - name: Create Gravity Forms Site for Testing in InstaWP
-        if: steps.compare-revisions.outputs.gravity_update_found == 'true'
+        if: steps.compare-revisions.outputs.gravityforms_update_found == 'true'
         uses: instawp/wordpress-testing-automation@main
         with:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
