added

diff --git a/.github/workflows/gravityforms&addons.yml b/.github/workflows/gravityforms&addons.yml
--- a/.github/workflows/gravityforms&addons.yml
+++ b/.github/workflows/gravityforms&addons.yml
@@ -90,7 +90,7 @@ jobs:
           cp "$current_revision_file" "$latest_revision_file"
       - name: Random Sleep Before Processing
         run: |
-          sleep_time=$(( RANDOM % 10 ))
+          sleep_time=$(( RANDOM % 8 ))
           echo "Sleeping for $sleep_time seconds..."
           sleep $sleep_time
 
@@ -101,42 +101,41 @@ jobs:
           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
           max_retries=5
           attempt=0
-          while [ $attempt -lt $max_retries ]; do
-            sleep_time=$(( RANDOM % 10 ))
-            echo "Sleeping for $sleep_time seconds..."
-            sleep $sleep_time
-            # Stash any unstaged changes before pulling
-            git stash --include-untracked
+          
+          sleep_time=$(( RANDOM % 10 ))
+          echo "Sleeping for $sleep_time seconds..."
+          sleep $sleep_time
+          # Stash any unstaged changes before pulling
+          git stash --include-untracked
 
-            # Pull the latest changes from the remote branch with rebase
-            git pull --rebase origin bug-fixes
+          # Pull the latest changes from the remote branch with rebase
+          git pull --rebase origin bug-fixes
 
-            # Apply the stashed changes back after the pull
-            git stash pop || echo "No changes to apply from stash"
+          # Apply the stashed changes back after the pull
+          git stash pop || echo "No changes to apply from stash"
 
-            # Add the updated revision file
-            git add ".revision/${{ matrix.plugin }}_latest_revision_gravityforms.txt"
+          # Add the updated revision file
+          git add ".revision/${{ matrix.plugin }}_latest_revision_gravityforms.txt"
 
-            # Check if there are any changes to commit
-            if ! git diff-index --quiet HEAD; then
-              git commit -m "Update ${{ matrix.plugin }} SVN revision"
-              
-              # Try to push changes
-              git push
-              if [ $? -eq 0 ]; then
-                echo "Successfully pushed changes."
-                break
-              else
-                echo "Push failed. Retrying..."
-              fi
-            else
-              echo "No changes to commit."
+          # Check if there are any changes to commit
+          if ! git diff-index --quiet HEAD; then
+            git commit -m "Update ${{ matrix.plugin }} SVN revision"
+            
+            # Try to push changes
+            git push
+            if [ $? -eq 0 ]; then
+              echo "Successfully pushed changes."
               break
+            else
+              echo "Push failed. Retrying..."
             fi
+          else
+            echo "No changes to commit."
+            break
+          fi
 
-            attempt=$((attempt + 1))
-            sleep 10  # Wait before retrying
-          done
+        
+          sleep 10  # Wait before retrying
           echo "Failed to push changes after $max_retries attempts."
           exit1
 
