added

diff --git a/.github/workflows/gravityforms&addons.yml b/.github/workflows/gravityforms&addons.yml
--- a/.github/workflows/gravityforms&addons.yml
+++ b/.github/workflows/gravityforms&addons.yml
@@ -660,12 +660,20 @@ jobs:
 
           # Check if there are any changes to commit
           if ! git diff-index --quiet HEAD; then
-            git commit -m "Update gf-hcaptcha SVN revision"
+            git commit -m "Update gfhcaptcha SVN revision"
             
-            # Try to push changes
-            git push
-            if [ $? -ne 0 ]; then
-              echo "Push failed."
+            # Retry logic for pushing changes
+            retries=3
+            for i in $(seq 1 $retries); do
+              git push && break || {
+                echo "Push failed. Attempt $i of $retries."
+                sleep 5
+                git fetch --prune
+                git rebase origin/bug-fixes
+              }
+            done
+            if [ $i -eq $retries ]; then
+              echo "Push failed after $retries attempts."
               exit 1
             fi
           else
